## Data Preprocessing

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plot

In [3]:
dataset = pd.read_csv('https://a.uguu.se/6M1p6nI0coox_Data.csv')
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [5]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values

In [6]:
print(X)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Missing Data

In [7]:
from sklearn.preprocessing import Imputer
imputer = Imputer(strategy='mean')
X[:, 1:] = imputer.fit_transform(X[:, 1:])
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

## LabelEncoder & OneHotEncoder

In [8]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
x_labelEncoder = LabelEncoder()
y_labelEncoder = LabelEncoder()
X[:, 0] = x_labelEncoder.fit_transform(X[:, 0])
y = y_labelEncoder.fit_transform(y)

oneHotEncoder = OneHotEncoder(categorical_features=[0])
X = oneHotEncoder.fit_transform(X).toarray()
X = X[:, 1:] #Dummy Variable Trap
print(X)
print(y)

[[0.00000000e+00 0.00000000e+00 4.40000000e+01 7.20000000e+04]
 [0.00000000e+00 1.00000000e+00 2.70000000e+01 4.80000000e+04]
 [1.00000000e+00 0.00000000e+00 3.00000000e+01 5.40000000e+04]
 [0.00000000e+00 1.00000000e+00 3.80000000e+01 6.10000000e+04]
 [1.00000000e+00 0.00000000e+00 4.00000000e+01 6.37777778e+04]
 [0.00000000e+00 0.00000000e+00 3.50000000e+01 5.80000000e+04]
 [0.00000000e+00 1.00000000e+00 3.87777778e+01 5.20000000e+04]
 [0.00000000e+00 0.00000000e+00 4.80000000e+01 7.90000000e+04]
 [1.00000000e+00 0.00000000e+00 5.00000000e+01 8.30000000e+04]
 [0.00000000e+00 0.00000000e+00 3.70000000e+01 6.70000000e+04]]
[0 1 0 0 1 1 0 1 0 1]


/srv/conda/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


## Train Test Split

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, y, random_state=0)

## Scaling

In [10]:
from sklearn.preprocessing import StandardScaler
x_scaler = StandardScaler()
X_train = x_scaler.fit_transform(X_train)
X_test = x_scaler.transform(X_test)

In [11]:
print(X_train)
print(Y_train)

[[ 0.         -0.8660254  -0.2029809   0.44897083]
 [ 0.          1.15470054 -1.82168936 -1.41706417]
 [ 0.          1.15470054  0.08478949 -1.0242147 ]
 [ 0.         -0.8660254   1.5775984   1.62751925]
 [ 0.          1.15470054 -0.04111006 -0.14030338]
 [ 0.         -0.8660254   0.93011502  0.94003267]
 [ 0.         -0.8660254  -0.52672259 -0.43494049]]
[1 1 0 1 0 0 1]
